### ISSUE TITLE
armory --check option should override num_eval_batches

### ISSUE THREAD

**Issue by mwartell** [twosixlabs/armory#1249]
In https://github.com/twosixlabs/armory/blob/39e07d30c275da53a1266cd01abb7c2b2d83a932/armory/scenarios/main.py#L232 there is a line that warns the `--check` option will override num_eval_batches but there is no code that actually implements that override.

**Comment by lcadalzo** [comment]
If you `armory run` with `--num-eval-batches` and `--check`, you get the following error:
```
File "/opt/conda/lib/python3.7/site-packages/armory/scenarios/scenario.py", line 46, in __init__
raise ValueError("check_run and num_eval_batches are incompatible")
ValueError: check_run and num_eval_batches are incompatible
```

so not only is the latter not overriding the former, but this isn't a combination that Armory allows. This popped up on my radar because I noticed that running a config which has `"num_eval_batches"` set in the `"sysconfig"` portion of the config yields the error above when you add only the `--check` flag. This feels counterinuitive, as I think I should be able to `armory run` any config with (only) the `--check` flag, which should then override `"num_eval_batches"` in the config

It seems reasonable that passing both `--check` and `--num-eval-batches` with `armory run` yields an error, but if I'm only passing the `--check` flag I don't think it should error

**Comment by shenshaw26** [comment]
@mwartell , I think we should punt on this ticket just a bit and include as a part of this PR: https://github.com/shenshaw26/armory/pull/6.  Thoughts?

**Comment by mwartell** [comment]
My mental design for the new Experiment and Environment handle these two options differently. In the same way that `use_gpu` and `gpus` suffer from "hard to explain" interactions so do these parameters.

As we made `--debug` a synonym for `--log armory:debug` so too could `--check` and `--num-eval-batches` become aliases to a more comprehensive parameter.

**Comment by shenshaw26** [comment]
I agree.... I guess I was saying that we should push this into that PR so that we address it there, along with the cleanup of the whole cli bits.  My vote would be to move towards something like `--override gpus=none` or `--override gpus=all` from the cli.  

And, as we have discussed, the overrides would have the following heirarchy:
- if nothing else is specified, the default environment and experiment parameters are used
- if the experiment file (aka scenario.json) specifies a parameter that will be used
- if user specifies `--override parameter=value` on the command line that will overrule the experiment file parameter

so then an experiment file could look like `test.aexp`:
```
# ###################################################################
#                  Base Image Classification Experiment
# This just creates a model and a dataset with no Attack
# or defense
####################################################################
---
_meta:
  name: base_image_classification.json
  author: S. Henshaw
  description: Blah

poison: null

attack: null

dataset:
  batch_size: 64
  framework: "numpy"
  module: "armory.data.datasets"
  name: "mnist"

metric: null

model:
  fit: true
  fit_kwargs:
    nb_epoch: 3
  model_kwargs: {}
  module: "armory.baseline_models.pytorch.mnist"
  name: "get_art_model"
  weights_file: null
  wrapper_kwargs: {}

scenario:
  kwargs: {}
  module_name: "armory.scenarios.image_classification"
  function_name: "ImageClassificationTask"

overrides: 
  - num_eval_batches=100
```
and user could run `armory run test.aexp` or they could run `armory run test.aexp --override num_eval_batches=2`.

Is there anything else that the `--check` flag was intended to change about the experiment?
